create table login_access (id integer generated by default as identity, attempts integer, expiry_date TIMESTAMP, last_login TIMESTAMP not null, status varchar(1) not null, token varchar(255), user_name varchar(50) not null, primary key (id))
create table phone (id integer generated by default as identity, city_code varchar(2) not null, country_code varchar(3) not null, creation_date TIMESTAMP not null, number varchar(12) not null, state varchar(1) not null, update_date TIMESTAMP, user_id integer not null, primary key (id))
create table user (id integer generated by default as identity, creation_date TIMESTAMP not null, email varchar(60) not null, name varchar(50) not null, password varchar(8) not null, state varchar(1) not null, update_date TIMESTAMP, user_name varchar(50) not null, primary key (id))
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
alter table user add constraint UK_lqjrcobrh9jc8wpcar64q1bfh unique (user_name)
alter table phone add constraint FKb0niws2cd0doybhib6srpb5hh foreign key (user_id) references user
